### ISSUE TITLE
Would it be more reasonable to modify the PackTxs function to stop when a certain size is reached? 

### ISSUE THREAD

**Issue by Lupinus** [HuangLab-SYSU/block-emulator#40]
`
func (tx *Transaction) Size() int {
	size := len(tx.Sender) + len(tx.Recipient) + 8 // Nonce is uint64, so 8 bytes
	size += len(tx.Signature) + tx.Value.BitLen()/8 + len(tx.TxHash)
	size += len(tx.Time.String()) + 1 // Relayed is a bool, 1 byte
	return size
}

// Pack transactions based on the total size
func (txpool *TxPool) PackTxs(maxSize int) []*Transaction {
	txpool.lock.Lock()
	defer txpool.lock.Unlock()

	var totalSize int
	var txsPacked []*Transaction

	for _, tx := range txpool.TxQueue {
		txSize := tx.Size()
		if totalSize+txSize > maxSize {
			break
		}
		txsPacked = append(txsPacked, tx)
		totalSize += txSize
	}

	// Adjust the tx queue
	txNum := len(txsPacked)
	txpool.TxQueue = txpool.TxQueue[txNum:]

	return txsPacked
}
`

**Comment by iiinotlll** [comment]
Thank you for your insightful suggestions!

In the current BlockEmulator, we use "BlockSize"(the number of transactions in a block) to limit the block size. 
Your code limits the block size by data size, which is a reasonable approach.

We will add this implementation to the open-source code so that users can choose the method based on their needs.
